"""
Generate the README evidence from a REAL run (needs GROQ_API_KEY in .env).

    python evidence.py

What it does, in-process through Flask's test client (no second terminal needed):
  1. Submits the four Milestone 4 test inputs and records both signal scores + combined result.
  2. Files an appeal on the borderline formal-human submission.
  3. Sends 12 rapid submissions to show the 10/minute rate limit (expect 10x 200, then 429).
  4. Pulls the most recent audit-log entries via GET /log.
Then writes docs/evidence.md and replaces the block between the EVIDENCE markers in README.md.
The real audit log is left at logs/audit_log.jsonl so it can be committed and linked.
"""
import json
import os
import re
import sys

import config

if not config.GROQ_API_KEY or config.GROQ_API_KEY.startswith("your_"):
    sys.exit("GROQ_API_KEY is not set. Add it to .env first (see .env.example).")

import app as app_module  # noqa: E402
from tests.samples import ALL  # noqa: E402

client = app_module.app.test_client()
limiter = app_module.limiter
out = []


def md(line=""):
    out.append(line)
    print(line)


# 1. The four test inputs ---------------------------------------------------
md("### Scores on the four Milestone 4 test inputs")
md()
md(f"Model: `{config.GROQ_MODEL}`. Generated by `python evidence.py`.")
md()
md("| Input | Words | LLM judge | Stylometry | Combined `ai_score` | `confidence` | Attribution |")
md("|---|---|---|---|---|---|---|")
results = {}
for name, text in ALL.items():
    limiter.reset()
    r = client.post("/submit", json={"text": text, "creator_id": f"evidence-{name}"}).get_json()
    results[name] = r
    llm = r["signals"]["llm_judge"]["score"]
    md(f"| {name} | {r['signals']['stylometry']['metrics']['words']} | "
       f"{'unavailable' if llm is None else f'{llm:.2f}'} | "
       f"{r['signals']['stylometry']['score']:.2f} | {r['ai_score']:.2f} | "
       f"{r['confidence']:.2f} | `{r['attribution']}` |")
md()

if any(r["signals"]["llm_judge"]["status"] != "ok" for r in results.values()):
    md("> ⚠️ The LLM signal was unavailable for at least one input. Check your API key and "
       "model name, then re-run before committing this evidence.")
    md()

# Two contrasting examples (highest vs. lowest confidence)
ranked = sorted(results.items(), key=lambda kv: kv[1]["confidence"], reverse=True)
hi_name, hi = ranked[0]
lo_name, lo = ranked[-1]
md("### Two submissions with noticeably different confidence")
md()
for title, name, r in (("Higher confidence", hi_name, hi), ("Lower confidence", lo_name, lo)):
    llm_j = r["signals"]["llm_judge"]
    md(f"**{title}: `{name}`**")
    md()
    md(f"> {ALL[name]}")
    md()
    md(f"- `attribution`: **{r['attribution']}**, `confidence`: **{r['confidence']:.2f}**, "
       f"`ai_score`: {r['ai_score']:.2f}")
    md(f"- LLM judge: {llm_j['score']} ({'; '.join(llm_j['indicators']) or 'no indicators'})")
    md(f"- Stylometry: {r['signals']['stylometry']['score']} — "
       f"`{json.dumps(r['signals']['stylometry']['components'])}`")
    if r["gate_note"]:
        md(f"- Gate note: {r['gate_note']}")
    md(f"- Label shown: \"{r['label']}\"")
    md()

# 2. Appeal ----------------------------------------------------------------
appeal_target = results["borderline_formal_human"]["content_id"]
a = client.post("/appeal", json={
    "content_id": appeal_target,
    "creator_reasoning": "I wrote this paragraph myself for my economics seminar paper; "
                         "it's formal because it's academic writing, not because it's AI.",
}).get_json()
md("### Appeal")
md()
md("```json")
md(json.dumps(a, indent=2, ensure_ascii=False))
md("```")
md()

# 3. Rate limit ------------------------------------------------------------
limiter.reset()
codes = []
for _ in range(12):
    resp = client.post("/submit", json={
        "text": "This is a test submission for rate limit testing purposes only.",
        "creator_id": "rate-test"})
    codes.append(resp.status_code)
last = resp.get_json()
md("### Rate limit: 12 rapid submissions (limit is 10 per minute)")
md()
md("```")
md("\n".join(str(c) for c in codes))
md("```")
md()
md(f"429 response body: `{json.dumps(last)}`")
md()
limiter.reset()

# 4. Audit log sample -------------------------------------------------------
entries = client.get("/log?limit=200").get_json()["entries"]
sample = [e for e in entries if e["event"] == "appeal"][:1]
sample += [e for e in entries if e["event"] == "submission"
           and e["creator_id"].startswith("evidence-")][:4]
md("### Audit log sample (from `GET /log`, newest first)")
md()
md("Full file: [`logs/audit_log.jsonl`](logs/audit_log.jsonl)")
md()
md("```json")
for e in sample:
    md(json.dumps(e, ensure_ascii=False))
md("```")

# Write outputs --------------------------------------------------------------
os.makedirs("docs", exist_ok=True)
with open("docs/evidence.md", "w", encoding="utf-8") as f:
    f.write("# Evidence from a real run\n\n" + "\n".join(out) + "\n")

with open("README.md", encoding="utf-8") as f:
    readme = f.read()
block = "<!-- EVIDENCE:START -->\n" + "\n".join(out) + "\n<!-- EVIDENCE:END -->"
new_readme, n = re.subn(r"<!-- EVIDENCE:START -->.*?<!-- EVIDENCE:END -->", lambda _: block,
                        readme, flags=re.DOTALL)
if n:
    with open("README.md", "w", encoding="utf-8") as f:
        f.write(new_readme)
    print("\nREADME.md evidence section updated. docs/evidence.md written.")
else:
    print("\nEVIDENCE markers not found in README.md; wrote docs/evidence.md only.")
